#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^ioncore:" ; then
    echo "Creating system group: ioncore"
    groupadd --system ioncore
fi

# add user
if ! getent passwd | grep -q "^ioncore:"; then
    echo "Creating ioncore system user"
    useradd --gid "ioncore" --system -m ioncore
fi

# build nodejs addons
cd "/usr/opt/ioncore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/ioncore/.ioncore/data"
chown -R ioncore:ioncore "/home/ioncore/.ioncore"

# start ioncore
if hash service 2> /dev/null; then
    service ioncore start || echo "ioncore could not be registered or started"
elif hash start 2> /dev/null; then
    start ioncore || echo "ioncore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "ioncore.service" && \
            systemctl start "ioncore.service"
    } || echo "ioncore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so ioncore could not be started'
fi
