#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service ioncore stop || echo "ioncore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "ioncore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "ioncore.service" || echo "ioncore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so ioncore could not be stopped"
fi
